# Generated by Django 3.2.18 on 2023-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
