# Generated by Django 3.2.18 on 2023-04-26 23:05

import django.contrib.auth.mixins
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=100, verbose_name='nome de usuário')),
                ('email', models.EmailField(db_index=True, max_length=90, unique=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('proprietario', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
